"""
Fragment API Python Library.

Async client for interacting with Fragment.com marketplace and Telegram services.
Supports Stars, Premium, Giveaways, Usernames, Numbers, and Gifts operations.
"""

from FragmentAPI.client import FragmentClient
from FragmentAPI.types import (
    AdsTopupResult,
    AuctionInfo,
    BatchItemResult,
    BatchResult,
    BidHistoryEntry,
    BidResult,
    ConfigurationError,
    CookieError,
    EvmInvoice,
    EvmPaymentResult,
    FragmentAPIError,
    FragmentError,
    FragmentPageError,
    GiftAttribute,
    GiftInfo,
    GiftsResult,
    GiveawayPremiumResult,
    GiveawayStarsResult,
    LoginCodeResult,
    NumberInfo,
    NumbersResult,
    OperationError,
    OwnerHistoryEntry,
    ParseError,
    PremiumPriceOption,
    PremiumPrices,
    PremiumResult,
    PremiumTransaction,
    PreparedTransaction,
    PreparedTransactionMessage,
    ProfileInfo,
    PurchaseItem,
    PurchaseResult,
    RecipientInfo,
    SessionInfo,
    StarsPrice,
    StarsPrices,
    StarsResult,
    StarsTransaction,
    TerminateSessionsResult,
    TransactionError,
    UnexpectedError,
    UsernameInfo,
    UsernamesResult,
    UserNotFoundError,
    VerificationError,
    WalletError,
    WalletInfo,
    AlreadySubscribedError,
    AnonymousNumberError,
)

__version__ = "10.0.0"
__author__ = "S1qwy"
__email__ = "S1qwy@internet.ru"

__all__ = [
    "__version__",
    "FragmentClient",
    "AdsTopupResult",
    "AlreadySubscribedError",
    "AnonymousNumberError",
    "AuctionInfo",
    "BatchItemResult",
    "BatchResult",
    "BidHistoryEntry",
    "BidResult",
    "ConfigurationError",
    "CookieError",
    "EvmInvoice",
    "EvmPaymentResult",
    "FragmentAPIError",
    "FragmentError",
    "FragmentPageError",
    "GiftAttribute",
    "GiftInfo",
    "GiftsResult",
    "GiveawayPremiumResult",
    "GiveawayStarsResult",
    "LoginCodeResult",
    "NumberInfo",
    "NumbersResult",
    "OperationError",
    "OwnerHistoryEntry",
    "ParseError",
    "PremiumPriceOption",
    "PremiumPrices",
    "PremiumResult",
    "PremiumTransaction",
    "PreparedTransaction",
    "PreparedTransactionMessage",
    "ProfileInfo",
    "PurchaseItem",
    "PurchaseResult",
    "RecipientInfo",
    "SessionInfo",
    "StarsPrice",
    "StarsPrices",
    "StarsResult",
    "StarsTransaction",
    "TerminateSessionsResult",
    "TransactionError",
    "UnexpectedError",
    "UsernameInfo",
    "UsernamesResult",
    "UserNotFoundError",
    "VerificationError",
    "WalletError",
    "WalletInfo",
]