'''
Fragment API Python Library v5.0.0
'''

from FragmentAPI.client import FragmentClient
from FragmentAPI.types import (
    AdsTopupResult,
    AuctionInfo,
    BidHistoryEntry,
    ConfigError,
    CookieError,
    FragmentAPIError,
    FragmentBaseError,
    FragmentPageError,
    GiftAttribute,
    GiftInfo,
    GiftsResult,
    GiveawayPremiumResult,
    GiveawayStarsResult,
    NumberInfo,
    NumbersResult,
    OperationError,
    OwnerHistoryEntry,
    ParseError,
    PremiumPriceOption,
    PremiumPrices,
    PremiumResult,
    PremiumTransaction,
    ProfileInfo,
    ProxyError,
    SessionInfo,
    StarsPrice,
    StarsPrices,
    StarsResult,
    StarsTransaction,
    TransactionError,
    UnexpectedError,
    UsernameInfo,
    UsernamesResult,
    UserNotFoundError,
    VerificationError,
    WalletError,
    WalletInfo,
)

__version__ = "5.0.0"
__author__ = "S1qwy"
__email__ = "S1qwy@internet.ru"

__all__ = [
    "__version__",
    "FragmentClient",
    "AdsTopupResult",
    "AuctionInfo",
    "BidHistoryEntry",
    "ConfigError",
    "CookieError",
    "FragmentAPIError",
    "FragmentBaseError",
    "FragmentPageError",
    "GiftAttribute",
    "GiftInfo",
    "GiftsResult",
    "GiveawayPremiumResult",
    "GiveawayStarsResult",
    "NumberInfo",
    "NumbersResult",
    "OperationError",
    "OwnerHistoryEntry",
    "ParseError",
    "PremiumPriceOption",
    "PremiumPrices",
    "PremiumResult",
    "PremiumTransaction",
    "ProfileInfo",
    "ProxyError",
    "SessionInfo",
    "StarsPrice",
    "StarsPrices",
    "StarsResult",
    "StarsTransaction",
    "TransactionError",
    "UnexpectedError",
    "UsernameInfo",
    "UsernamesResult",
    "UserNotFoundError",
    "VerificationError",
    "WalletError",
    "WalletInfo",
]