"""
Fragment API Python Library.

Async client for interacting with Fragment.com marketplace and Telegram services.
Supports Stars, Premium, Giveaways, Usernames, Numbers, and Gifts operations.
"""

from FragmentAPI.client import FragmentClient
from FragmentAPI.storage.base import SessionStorage
from FragmentAPI.storage.file import FileSessionStorage
from FragmentAPI.storage.redis import RedisSessionStorage
from FragmentAPI.types.models import (
    AdsTopupResult,
    AdsWithdrawalConfirmResult,
    AdsWithdrawalInitResult,
    AuctionInfo,
    BatchItemResult,
    BatchResult,
    BidHistoryEntry,
    BidResult,
    EvmInvoice,
    EvmPaymentResult,
    GatewayPriceInfo,
    GatewayRechargeResult,
    GiftAttribute,
    GiftInfo,
    GiftsResult,
    GiveawayPremiumResult,
    GiveawayStarsResult,
    LoginCodeResult,
    NumberInfo,
    NumbersResult,
    OfferResult,
    OwnerHistoryEntry,
    OfferHistoryEntry,
    PremiumPriceOption,
    PremiumPrices,
    PremiumResult,
    PremiumTransaction,
    PreparedTransaction,
    PreparedTransactionMessage,
    ProfileInfo,
    PurchaseItem,
    PurchaseResult,
    RecipientInfo,
    SessionInfo,
    StarsPrice,
    StarsPrices,
    StarsResult,
    StarsTransaction,
    SubscriptionResult,
    TerminateSessionsResult,
    TransactionResult,
    UsernameInfo,
    UsernamesResult,
    WalletInfo,
)
from FragmentAPI.exceptions import (
    AlreadySubscribedError,
    AnonymousNumberError,
    ConfigurationError,
    CookieError,
    FragmentAPIError,
    FragmentError,
    FragmentPageError,
    OperationError,
    ParseError,
    RetryExhaustedError,
    SessionStorageError,
    TransactionError,
    UnexpectedError,
    UserNotFoundError,
    VerificationError,
    WalletError,
)

__version__ = "11.0.0"
__author__ = "S1qwy"
__email__ = "S1qwy@internet.ru"

__all__ = [
    "__version__",
    "FragmentClient",
    "SessionStorage",
    "FileSessionStorage",
    "RedisSessionStorage",
    "AdsTopupResult",
    "AdsWithdrawalConfirmResult",
    "AdsWithdrawalInitResult",
    "AlreadySubscribedError",
    "AnonymousNumberError",
    "AuctionInfo",
    "BatchItemResult",
    "BatchResult",
    "BidHistoryEntry",
    "BidResult",
    "ConfigurationError",
    "CookieError",
    "EvmInvoice",
    "EvmPaymentResult",
    "FragmentAPIError",
    "FragmentError",
    "FragmentPageError",
    "GatewayPriceInfo",
    "GatewayRechargeResult",
    "GiftAttribute",
    "GiftInfo",
    "GiftsResult",
    "GiveawayPremiumResult",
    "GiveawayStarsResult",
    "LoginCodeResult",
    "NumberInfo",
    "NumbersResult",
    "OfferResult",
    "OperationError",
    "OwnerHistoryEntry",
    "OfferHistoryEntry",
    "ParseError",
    "PremiumPriceOption",
    "PremiumPrices",
    "PremiumResult",
    "PremiumTransaction",
    "PreparedTransaction",
    "PreparedTransactionMessage",
    "ProfileInfo",
    "PurchaseItem",
    "PurchaseResult",
    "RecipientInfo",
    "RetryExhaustedError",
    "SessionInfo",
    "SessionStorageError",
    "StarsPrice",
    "StarsPrices",
    "StarsResult",
    "StarsTransaction",
    "SubscriptionResult",
    "TerminateSessionsResult",
    "TransactionError",
    "TransactionResult",
    "UnexpectedError",
    "UsernameInfo",
    "UsernamesResult",
    "UserNotFoundError",
    "VerificationError",
    "WalletError",
    "WalletInfo",
]